#%RAML 1.0 NamedExample
[
              {
               catagoryID: 123,
               catagoryType: "Electronics",
               categoryName: "laptop"
               

              },

              
              {
               catagoryID: 456,
               catagoryType: "Electronics",
               categoryName: "mouse"
               

              }
            ]
