#%RAML 1.0 NamedExample

    [
      {
        "categoryid": 11,
        "productid": 1,
        "description": "core i5",
        "name": "dell laptop",
        "price": 1000,
        "video_url": "www.dell.com"
      },
      {
        "categoryid": 12,
        "productid": 2,
        "description": "core i3",
        "name": "HP laptop",
        "price": 800,
        "video_url": "www.hp.com"
      }
  ]